version: "3.8"

services:
  database:
    container_name: database
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/todo-app
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/todo-app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  pgadmin:
    container_name: pgamin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kavdavidnann1993@gmail.com
      PGADMIN_DEFAULT_PASSWORD: main
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - database
